set(GLEW_PATH ${SHIROIENGINE_LIBS_DIR}/glew)
set(GLEW_INCLUDE_DIR ${GLEW_PATH}/include)
set(BUILD_UTILS OFF CACHE BOOL "Remove glew utils")
if (NOT EXISTS ${GLEW_INCLUDE_DIR})
    set(GENERATE_GLEW_SCRIPT ${CMAKE_HOME_DIRECTORY}/scripts/generateGLEW.sh)
    execute_process(COMMAND bash ${GENERATE_GLEW_SCRIPT} WORKING_DIRECTORY ${GLEW_PATH} RESULT_VARIABLE R)
endif ()
add_subdirectory(${GLEW_PATH}/build/cmake ${CMAKE_BINARY_DIR}/glew)
foreach(t glew glew_s)
    target_include_directories(${t} PUBLIC $<BUILD_INTERFACE:${GLEW_INCLUDE_DIR}>)
endforeach()